import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

import Footer from "@/widgets/app-footer/footer";
import Header from "@/widgets/app-header/header";

const jet= JetBrains_Mono({
	variable: "--font-jetbrains-mono",
	subsets: ["latin"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jet.variable} flex flex-col justify-between bg-background bg-gradient-to-r from-primary-from to-primary-to min-h-screen overflow-x-hidden antialiased`}      >
        <header className="py-4">
          <Header/>
        </header>
        <main>
          {children}
        </main>
        <footer className="py-4">
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
